# Generated by Django 2.2.7 on 2019-11-05 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('nome_fantasia', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('cadastro', models.DateField(auto_now_add=True)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=78)),
                ('cidade', models.CharField(blank=True, max_length=78)),
                ('uf', models.CharField(blank=True, max_length=8)),
                ('cep', models.CharField(blank=True, max_length=20)),
                ('contato', models.CharField(blank=True, max_length=78)),
                ('tel', models.CharField(blank=True, max_length=32)),
                ('celular', models.CharField(blank=True, max_length=32)),
                ('fax', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cnpj', models.CharField(blank=True, max_length=32)),
                ('ie', models.CharField(blank=True, max_length=32)),
                ('cpf', models.CharField(blank=True, max_length=32)),
                ('rg', models.CharField(blank=True, max_length=32)),
                ('observacoes', models.TextField(blank=True)),
                ('endereco_entrega', models.CharField(blank=True, max_length=200)),
                ('bairro_entrega', models.CharField(blank=True, max_length=78)),
                ('cidade_entrega', models.CharField(blank=True, max_length=78)),
                ('uf_entrega', models.CharField(blank=True, max_length=8)),
                ('cep_entrega', models.CharField(blank=True, max_length=20)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
